#!/bin/bash
#
# Build Debian packages inside Linux namespaces.
#
# Copyright (c) 2013, Alessandro Ghedini
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
# IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

set -e

UNSTABLE_CODENAME="sid"
TESTING_CODENAME="jessie"
STABLE_CODENAME="wheezy"

DEBIAN_SUITES=(
	$UNSTABLE_CODENAME $TESTING_CODENAME $STABLE_CODENAME
	"experimental" "unstable" "testing" "stable" "oldstable"
)

if [ -z "${DIST}" ] && [ -r "debian/changelog" ]; then
	DIST=$(dpkg-parsechangelog | awk '/^Distribution: / {print $2}')
fi

: ${DIST:="$(lsb_release --short --codename)"}

case "$DIST" in
	$UNSTABLE_CODENAME)
		DIST="unstable"
		;;
	$TESTING_CODENAME)
		DIST="testing"
		;;
	$STABLE_CODENAME)
		DIST="stable"
		;;
esac

: ${ARCH:="$(dpkg --print-architecture)"}

NAME="$DIST-$ARCH"
ARCHITECTURE="${ARCH}"

BASEDIR="/var/cache/pflask/base-$NAME"

BUILDDIR=$(pwd)
PKGDIR=$(basename $BUILDDIR)
RESDIR=$(dirname $BUILDDIR)

SRC=$(dpkg-parsechangelog | sed -rne 's,^Source: (.+).*,\1,p')
VER=$(dpkg-parsechangelog | sed -rne 's,^Version: ([0-9]:)*(.+).*,\2,p')

OVERLAY="$RESDIR/$PKGDIR-XXXX"

OVERLAY=$(mktemp -d $OVERLAY)

USER=$(whoami)

PFLASK_TOOL="sudo $(which pflask) --no-userns"
APT_TOOL="apt-get --no-install-recommends -y"
TOOLS_TOOL="$APT_TOOL install devscripts equivs fakeroot"
BDEPS_TOOL="mk-build-deps -r -i debian/control -t '$APT_TOOL'"
BUILD_TOOL="dpkg-buildpackage -tc -rfakeroot"
CLEAN_TOOL="debclean"
CHOWN_TOOL="sudo chown -f"
DSIGN_TOOL="debsign"

if [ ! -d "$BASEDIR" ]; then
	echo "E: Missing base root directory '$BASEDIR'"
	exit -1
fi

BUILD_CMD="$TOOLS_TOOL && $BDEPS_TOOL && $BUILD_TOOL"

$PFLASK_TOOL --root $BASEDIR			\
	--mount "tmp,$OVERLAY"			\
	--mount "aufs,$OVERLAY,$BASEDIR"	\
	--mount "bind,$RESDIR,$BASEDIR/mnt"	\
	--chdir "/mnt/$PKGDIR"			\
	--					\
	sh -c "$BUILD_CMD"

CHANGES="$RESDIR/${SRC}_${VER}_${ARCH}.changes"
DSC="$RESDIR/${SRC}_${VER}.dsc"
DEB="$RESDIR/${SRC}_${VER}.debian.tar.gz"
DIF="$RESDIR/${SRC}_${VER}.diff.tar.gz"

if [ -f "$DEB" ]; then
	$CHOWN_TOOL "$USER:$USER" $DEB
fi

if [ -f "$DIF" ]; then
	$CHOWN_TOOL "$USER:$USER" $DIF
fi

for PKG in `dh_listpackages`;
do
	FILE_ARCH="$RESDIR/${PKG}_${VER}_${ARCH}.deb"
	FILE_ALL="$RESDIR/${PKG}_${VER}_all.deb"

	if [ -f "$FILE_ARCH" ]; then
		$CHOWN_TOOL "$USER:$USER" $FILE_ARCH
	fi

	if [ -f "$FILE_ALL" ]; then
		$CHOWN_TOOL "$USER:$USER" $FILE_ALL
	fi
done

$CHOWN_TOOL "$USER:$USER" "$CHANGES"

$CHOWN_TOOL "$USER:$USER" "$DSC"

$DSIGN_TOOL "$CHANGES"

sudo rm -rf $OVERLAY

exit $?
