#!/bin/bash
#
# Build Debian packages inside Linux namespaces.
#
# Copyright (c) 2013, Alessandro Ghedini
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
# IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

set -e

UNSTABLE_CODENAME="sid"
TESTING_CODENAME="jessie"
STABLE_CODENAME="wheezy"

DEBIAN_SUITES=(
	$UNSTABLE_CODENAME $TESTING_CODENAME $STABLE_CODENAME
	"experimental" "unstable" "testing" "stable" "oldstable"
)

if [ -z "${DIST}" ] && [ -r "debian/changelog" ]; then
	DIST=$(dpkg-parsechangelog | awk '/^Distribution: / {print $2}')
fi

: ${DIST:="$(lsb_release --short --codename)"}

case "$DIST" in
	$UNSTABLE_CODENAME)
		DIST="unstable"
		;;
	$TESTING_CODENAME)
		DIST="testing"
		;;
	$STABLE_CODENAME)
		DIST="stable"
		;;
esac

: ${ARCH:="$(dpkg --print-architecture)"}

NAME="$DIST-$ARCH"
ARCHITECTURE="${ARCH}"

BASEDIR="/var/cache/pflask/base-$NAME"

BUILDDIR=$(pwd)
OVERDIR="/mnt"
PKGDIR=$(basename $BUILDDIR)
RESDIR=$(dirname $BUILDDIR)
TMPDIR="/mnt"

SRC=$(dpkg-parsechangelog | sed -rne 's,^Source: (.+).*,\1,p')
VER=$(dpkg-parsechangelog | sed -rne 's,^Version: ([0-9]:)*(.+).*,\2,p')

CHANGES_FILE="${SRC}_${VER}_${ARCH}.changes"
DSC_FILE="${SRC}_${VER}.dsc"
DEBIAN_FILE="${SRC}_${VER}.debian.tar.gz"
DIFF_FILE="${SRC}_${VER}.diff.tar.gz"

PFLASK_TOOL="sudo $(which pflask) --no-userns"
APT_TOOL="apt-get --no-install-recommends -y"
TOOLS_TOOL="$APT_TOOL install devscripts equivs fakeroot lintian"
BDEPS_TOOL="mk-build-deps -r -i debian/control -t '$APT_TOOL'"
BUILD_TOOL="dpkg-buildpackage -tc -rfakeroot"
LINT_TOOL="echo lintian: start && lintian  --allow-root -IE --pedantic ../$CHANGES_FILE && echo lintian: end"
CHOWN_TOOL="chown --from=root:root"
DSIGN_TOOL="debsign"

if [ ! -d "$BASEDIR" ]; then
	echo "E: Missing base root directory '$BASEDIR'"
	exit -1
fi

BUILD_CMD="$TOOLS_TOOL && $BDEPS_TOOL && $BUILD_TOOL; FAIL=\$?"
BUILD_CMD="$BUILD_CMD && $CHOWN_TOOL -R $UID:$UID $TMPDIR/$PKGDIR"

FILES="$CHANGES_FILE $DSC_FILE $DEBIAN_FILE $DIFF_FILE"

for PKG in `dh_listpackages`;
do
	FILES="$FILES ${PKG}_${VER}_${ARCH}.deb"
	FILES="$FILES ${PKG}_${VER}_all.deb"
done

for FILE in $FILES
do
	BUILD_CMD="$BUILD_CMD && [ -f $TMPDIR/$FILE ] && $CHOWN_TOOL $UID:$UID $TMPDIR/$FILE || true"
done

BUILD_CMD="$BUILD_CMD && [ \$FAIL = 0 ] && $LINT_TOOL"

$PFLASK_TOOL --root $BASEDIR				\
	--mount "tmp,$OVERDIR"				\
	--mount "aufs,$OVERDIR,$BASEDIR"		\
	--mount "bind,$RESDIR,$BASEDIR${TMPDIR}"	\
	--chdir "/mnt/$PKGDIR"				\
	--						\
	sh -c "$BUILD_CMD"

$DSIGN_TOOL "$RESDIR/$CHANGES_FILE"
