.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PFLASK\-DEBUILD" "1" "December 2013" "" ""
.
.SH "NAME"
\fBpflask\-debuild\fR \- build Debian packages inside Linux namespace containers
.
.SH "SYNOPSIS"
\fBpflask\-debuild\fR
.
.SH "DESCRIPTION"
\fBpflask\-debuild\fR is a wrapper aroung pflask that builds Debian packages inside a Linux namespace container\. It is also able to run \fBlintian(1)\fR on the generated \.changes file and sign the resulting package using \fBdebsign(1)\fR\.
.
.SH "ENVIRONMENT"
\fBDIST\fR
.
.P
\~\~\~\~\~\~ The Debian release (e\.g\. \fI"unstable"\fR)\. It will be used when searching for the base Debian install under \fB/var/cache/pflask\fR\. By default will be read from the \fBdebian/changelog\fR of the package to be built\.
.
.P
\fBARCH\fR
.
.P
\~\~\~\~\~\~ The Debian architecture (e\.g\. \fI"amd64"\fR)\. It will be used when searching for the base Debian install under \fB/var/cache/pflask\fR\. If none is specified, \fBdpkg\-architecture(1)\fR is used\.
.
.P
\fBDEBUILD_DPKG_BUILDPACKAGE_OPTS\fR
.
.P
\~\~\~\~\~\~ Options that should be passed to \fBdpkg\-buildpackage(1)\fR\.
.
.P
\fBDEBUILD_LINTIAN\fR
.
.P
\~\~\~\~\~\~ If set to \fI"yes"\fR (default) \fBlintian(1)\fR will be run\.
.
.P
\fBDEBUILD_LINTIAN_OPTS\fR
.
.P
\~\~\~\~\~\~ Options that should be passed to \fBlintian(1)\fR (by default \fI"\-IE \-\-pedantic"\fR will be used)\.
.
.SH "FILES"
\fB~/\.devscripts\fR
.
.P
\~\~\~\~\~\~ User\-specific configuration file\.
.
.P
\fB/etc/devscripts\.conf\fR
.
.P
\~\~\~\~\~\~ System\-wide configuration file\.
.
.SH "AUTHOR"
Alessandro Ghedini \fIalessandro@ghedini\.me\fR
.
.SH "COPYRIGHT"
Copyright (C) 2013 Alessandro Ghedini \fIalessandro@ghedini\.me\fR
.
.P
This program is released under the 2 clause BSD license\.
